### ISSUE TITLE
Remove ramda package and replace it with vanilla JS helpers

### ISSUE THREAD

**Issue by AbhayVAshokan** [bigbinary/neeto-filters-frontend#17]
Having `ramda` as a peer dependency forces the parent project to install `ramda`. Since we are in the process of moving away from ramda (Ref: https://github.com/bigbinary/wheel/issues/816), it will be better to remove the package from `neetoFilters`.

low-priority _t

**Comment by AbhayVAshokan** [comment]
Closing this issue, for now, the decision to remove `ramda` from neeto products is yet to be finalized.

**Comment by neerajdotname** [comment]
We are not going to replace `ramda` with vanila JS. Not need to reinvent lodash. Use lodash or the adventurous folks can try https://github.com/lodash/lodash/wiki/FP-Guide
